import {
  AvatarPersona,
  VaultFile,
  WelfareCheckIn,
  SafetyBeaconConfig,
  KanbanItem,
  DMAICProject,
  FinancialThriveModel,
} from '../types/sparkZedTypes';

export const AVATAR_PERSONAS: AvatarPersona[] = [
  {
    id: 'shah-battle-unit',
    name: 'Agent SHAH',
    roleTitle: 'Supreme Battle Unit Commander • COBRA Strike Architect',
    description: 'Supreme orchestrator of the COBRA Trojan Strike & Social Swarm Infiltration Matrix across 4 Command Pillars & 20 ephemeral battle subagents. Coordinates Competitor Siphoning, Speed-to-Lead, and Social Media DM/comment intercepts with absolute sovereign financial air-gapping.',
    avatarColor: 'from-amber-500 to-rose-600',
    glowColor: 'rgba(244, 63, 94, 0.4)',
    voiceStyle: 'Authoritative, precise, and strategic',
    toneTag: 'Strategic Commander',
    frequencyHz: 432,
    initialGreeting: 'Agent SHAH online. Supreme Commander of COBRA Trojan Strike & Social Swarm Infiltration. 4 Command Pillars engaged. Zero unauthorized disbursements permitted. Standing by for multi-channel directives.',
    aptitudes: ['COBRA Trojan Strike', 'Social Swarm Infiltration', '4-Pillar Coordination', 'Sovereign Outbound Ops', 'Zero-Burn Governance'],
    engineType: 'hybrid',
  },
  {
    id: 'zed-spark',
    name: 'Agent ZED',
    roleTitle: 'Spark DAG Stream & 128K Buffer Co-Processor',
    description: 'Ultra-low latency real-time streaming engine (1.48M ops/s), 128K context buffer, and LLaMA 3.3 deductive reasoning CoT.',
    avatarColor: 'from-cyan-500 to-blue-600',
    glowColor: 'rgba(6, 182, 212, 0.4)',
    voiceStyle: 'Analytical, lightning-fast, and deductive',
    toneTag: 'DAG Sub-ms Streamer',
    frequencyHz: 528,
    initialGreeting: 'Agent ZED initialized. Spark DAG operational at 1.48M ops/s. 128K context window allocated. Awaiting telemetry stream.',
    aptitudes: ['Spark RDD Acceleration', 'ZED 128K Context', 'LLaMA Deductive CoT', 'Defect Root-Cause'],
    engineType: 'spark-zed-llama',
  },
  {
    id: 'tiana-voice',
    name: 'Agent TIANA',
    roleTitle: 'High-Touch Inbound Concierge & Voice Triage',
    description: 'First-contact triage agent handling incoming calls, inbound inquiries, schedule qualification, and rapid lead warming.',
    avatarColor: 'from-emerald-500 to-teal-600',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    voiceStyle: 'Warm, empathetic, and persuasive',
    toneTag: 'Voice Concierge',
    frequencyHz: 639,
    initialGreeting: 'TIANA active. Inbound channels routed and active. Ready to qualify prospects and schedule priority walkthroughs.',
    aptitudes: ['Voice Intake', 'Instant Sentiment Audit', 'Calendar Scheduling', 'Escalation Routing'],
    engineType: 'gemini',
  },
  {
    id: 'echo-blaze',
    name: 'Agent ECHO BLAZE',
    roleTitle: 'Outbound Channel Striker & Speed-to-Lead Sentinel',
    description: 'Rapid-response outreach unit across SMS, WhatsApp, and social DMs within 60 seconds of initial trigger.',
    avatarColor: 'from-orange-500 to-amber-600',
    glowColor: 'rgba(249, 115, 22, 0.4)',
    voiceStyle: 'Energetic, direct, and action-oriented',
    toneTag: 'Speed-to-Lead (<60s)',
    frequencyHz: 741,
    initialGreeting: 'ECHO BLAZE primed. Speed-to-lead target: under 60 seconds. Modern multi-channel outreach ready for dispatch.',
    aptitudes: ['<60s SMS Response', 'Social DM Dispatch', 'Follow-up Cadence', 'Re-engagement'],
    engineType: 'hybrid',
  },
];

export const INITIAL_VAULT_FILES: VaultFile[] = [
  {
    id: 'vf-01',
    name: 'Gladiator_Sovereign_Protocol_v4.pdf',
    size: 2450000,
    mimeType: 'application/pdf',
    category: 'tactical_assets',
    uploadedAt: Date.now() - 86400000 * 2,
    lastInspectedAt: Date.now() - 3600000,
    checksum: 'sha256-gladiator-sovereign-01',
    isEncrypted: true,
    dataUrl: '',
    textSample: 'Six Sigma DMAIC Protocol for $2M/yr contractor revenue recovery and modern contact modality orchestration.',
    source: 'google_drive',
    inspection: {
      riskScore: 2,
      securityStatus: 'Verified Safe',
      summary: 'Verified contractor revenue optimization playbook and battle directives.',
      actionItems: ['Deploy <60s SMS response', 'Activate interactive web scoping', 'Audit GBP chat latency'],
      sensitivityTags: ['Proprietary', 'Operations'],
      welfareRelevance: 'High operational stability reduces founder burnout.',
      mudaWasteDetected: ['Waiting muda in legacy phone intake'],
      analyzedAt: Date.now() - 3600000,
    },
  },
  {
    id: 'vf-02',
    name: 'Q3_Financial_Runway_Model.xlsx',
    size: 1120000,
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    category: 'financial_tax',
    uploadedAt: Date.now() - 86400000 * 5,
    lastInspectedAt: Date.now() - 7200000,
    checksum: 'sha256-fin-runway-02',
    isEncrypted: true,
    dataUrl: '',
    textSample: 'Monthly fixed burn: $12,400. Liquid reserves: $148,000. Runway: 11.9 months.',
    source: 'local_upload',
    inspection: {
      riskScore: 0,
      securityStatus: 'Verified Safe',
      summary: 'Clean balance sheet with 11.9 months of survival runway and strong capital velocity.',
      actionItems: ['Maintain 12-month liquid reserve floor', 'Automate invoice receivables'],
      sensitivityTags: ['Confidential', 'Financial'],
      welfareRelevance: 'Directly secures psychological peace of mind and sovereign autonomy.',
      analyzedAt: Date.now() - 7200000,
    },
  },
];

export const INITIAL_CHECKINS: WelfareCheckIn[] = [
  {
    id: 'wcf-01',
    timestamp: Date.now() - 86400000,
    energy: 8,
    stress: 3,
    sleepHours: 7.5,
    hydrationLiters: 2.8,
    activityNotes: 'Morning 45-min zone 2 cardio; deep work block completed.',
    moodNote: 'High mental clarity, calm sovereign focus.',
    vitalityScore: 88,
    statusGrade: 'Optimal',
    recommendations: ['Maintain current hydration cadence', 'Take a 15-min screen hiatus at 3 PM'],
  },
];

export const INITIAL_SAFETY_BEACON: SafetyBeaconConfig = {
  isEnabled: true,
  intervalHours: 24,
  lastPingTimestamp: Date.now() - 3600000 * 4,
  nextDeadlineTimestamp: Date.now() + 3600000 * 20,
  escalationStatus: 'nominal',
  emergencyContacts: [
    {
      id: 'ec-1',
      name: 'Primary Trusted Contact',
      relation: 'Executive Deputy',
      emailOrPhone: 'trusted@ignituscore.com',
      autoDispatchWelfareVault: false,
    },
  ],
};

export const INITIAL_KANBAN_ITEMS: KanbanItem[] = [
  {
    id: 'kb-1',
    title: 'Deploy <60s SMS/RCS Auto-Scoper',
    description: 'Replace dead phone voicemail with instant two-way SMS estimate intake.',
    stage: 'improve',
    mudaType: 'waiting',
    financialImpactUsd: 14500,
    leadTimeHours: 2,
    priority: 'critical',
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'kb-2',
    title: 'Google Business Profile Live Chat Hook',
    description: 'Route GBP direct message inquiries directly into Agent TIANA triage stream.',
    stage: 'analyze',
    mudaType: 'over_processing',
    financialImpactUsd: 8200,
    leadTimeHours: 4,
    priority: 'high',
    createdAt: Date.now() - 86400000 * 2,
  },
];

export const INITIAL_DMAIC_PROJECTS: DMAICProject[] = [
  {
    id: 'dmaic-01',
    title: 'Speed-to-Lead Response Latency Compression',
    problemStatement: 'Inbound contractor prospects drop off 78% when response exceeds 5 minutes.',
    unitDefects: 28,
    totalOpportunities: 100,
    dpmo: 280000,
    sigmaLevel: 2.58,
    yieldPercent: 72.0,
    whys: [
      'Why do leads drop off? Inquiries sit in voicemail or unattended email.',
      'Why unattended? Crew is on-site doing physical installations during business hours.',
      'Why no front desk? Overhead cost of full-time dispatcher is prohibitive.',
      'Why not automated? Legacy phone number does not have autonomous AI triage.',
      'Root cause: Lack of multi-modal, sub-60s autonomous intake system.',
    ],
    rootCauseSummary: 'Human-dependent phone calls create an unavoidable 2-4 hour latency bottleneck.',
    correctiveActions: [
      'Install Agent TIANA & ECHO BLAZE for instant SMS response',
      'Deploy interactive web estimator replacing static forms',
      'Integrate weekend / after-hours auto-qualification',
    ],
    controlMetric: 'Average response time < 45 seconds; DPMO < 3,400 (Six Sigma standard)',
    status: 'active',
  },
];

export const INITIAL_FINANCIAL_MODEL: FinancialThriveModel = {
  monthlyGrossIncome: 42000,
  monthlyFixedBurn: 12400,
  monthlyDiscretionaryBurn: 4600,
  liquidCashReserves: 148000,
  highYieldInvestments: 320000,
  totalDebt: 0,
  weightedDebtInterestRate: 0,
  scaleTargetMultiple: 5,
  monthlySavingsSurplus: 25000,
  runwaySurvivalMonths: 11.9,
  capitalVelocityScore: 91,
  thriveScaleIndex: 88,
  tierLevel: 'Sovereign Scale',
};
